# Generated by Django 4.2.7 on 2023-12-04 15:18

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('next_delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('sku', models.IntegerField()),
                ('brand', models.CharField(max_length=1000)),
                ('vendor', models.CharField(max_length=1000)),
                ('unit_delivery_quantity', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('delivery_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.deliverytype')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_floor', models.BooleanField(default=True)),
                ('c_area', models.CharField(max_length=3)),
                ('c_aisle', models.IntegerField()),
                ('c_section', models.CharField(max_length=2)),
                ('c_row', models.IntegerField()),
                ('c_column', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('no_location', models.BooleanField(default=False)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_order_price', models.IntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.delivery')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='inventory',
            field=models.ManyToManyField(through='inventory.InventoryDeliveryRecord', to='inventory.inventory'),
        ),
    ]
