# Generated by Django 4.2.7 on 2023-11-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(default='apple', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='delivery_type',
            field=models.CharField(choices=[('default', 'Default'), ('cold-chain', 'Cold Chain'), ('third-party', 'Third Party')], default='default', max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='pink charger', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='sale_price',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.IntegerField(default=76554689976),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_delivery_quantity',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='vendor',
            field=models.CharField(default='global cellutions distributors', max_length=1000),
            preserve_default=False,
        ),
    ]
