# Generated by Django 4.2.7 on 2023-11-15 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_brand_inventory_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='c_aisle',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='c_area',
            field=models.CharField(default='01D', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='c_column',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='c_row',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='c_section',
            field=models.CharField(default='0A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='is_floor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='no_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='quantity',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
