# Generated by Django 5.0 on 2023-12-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorydeliveryrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(max_length=10),
        ),
    ]
