# Generated by Django 5.0 on 2023-12-18 05:24

import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('next_delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
