# Generated by Django 5.0 on 2024-01-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deliveries.deliverytype'),
            preserve_default=False,
        ),
    ]
